using System;
using System.Collections.Generic;

/*

> 11/01/2011 SM 387
- Criado propriedade CompatibilidadeVersao em Template, para definir qual a versão que será gerado os comentários em todos os objetos gerados pelo pattern
 
*/
namespace Heurys.Patterns.HPattern.Resources
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	public static class Messages
	{
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
				
		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heurys.Patterns.HPattern.Resources.Messages", typeof(Messages).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture 
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}
		
		private static Dictionary<string, WeakReference> resourceCache = new Dictionary<string, WeakReference>();
		
		internal static void ClearCache()
		{
			resourceCache.Clear();
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Action &apos;Export&apos; cannot be in a component that is not a grid.'
		/// </summary>
		public static System.String ActionExportNotInGrid
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("ActionExportNotInGrid", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["ActionExportNotInGrid"] = new WeakReference(ResourceManager.GetString("ActionExportNotInGrid", resourceCulture)); 

				return (System.String)resourceCache["ActionExportNotInGrid"].Target;
			}
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Action &apos;{0}&apos; doesn&apos;t have a GeneXus object to invoke.'
		/// </summary>
		public static System.String ActionNeedsObject
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("ActionNeedsObject", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["ActionNeedsObject"] = new WeakReference(ResourceManager.GetString("ActionNeedsObject", resourceCulture)); 

				return (System.String)resourceCache["ActionNeedsObject"].Target;
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Action &apos;{0}&apos; doesn&apos;t have a GeneXus object to invoke.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatActionNeedsObject(object arg0)
		{
			return FormatActionNeedsObject(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Action &apos;{0}&apos; doesn&apos;t have a GeneXus object to invoke.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatActionNeedsObject(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ActionNeedsObject, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Parent of action &apos;{0}&apos; is not an IHPatternComponent instance.'
		/// </summary>
		public static System.String ActionNotInComponent
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("ActionNotInComponent", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["ActionNotInComponent"] = new WeakReference(ResourceManager.GetString("ActionNotInComponent", resourceCulture)); 

				return (System.String)resourceCache["ActionNotInComponent"].Target;
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parent of action &apos;{0}&apos; is not an IHPatternComponent instance.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatActionNotInComponent(object arg0)
		{
			return FormatActionNotInComponent(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parent of action &apos;{0}&apos; is not an IHPatternComponent instance.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatActionNotInComponent(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ActionNotInComponent, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Context variable &apos;{0}&apos; must be based on an attribute, domain, or SDT.'
		/// </summary>
		public static System.String ContextVariableInvalidType
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("ContextVariableInvalidType", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["ContextVariableInvalidType"] = new WeakReference(ResourceManager.GetString("ContextVariableInvalidType", resourceCulture)); 

				return (System.String)resourceCache["ContextVariableInvalidType"].Target;
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Context variable &apos;{0}&apos; must be based on an attribute, domain, or SDT.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatContextVariableInvalidType(object arg0)
		{
			return FormatContextVariableInvalidType(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Context variable &apos;{0}&apos; must be based on an attribute, domain, or SDT.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatContextVariableInvalidType(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ContextVariableInvalidType, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Current Settings have not been set.'
		/// </summary>
		public static System.String CurrentSettingsNotSet
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("CurrentSettingsNotSet", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["CurrentSettingsNotSet"] = new WeakReference(ResourceManager.GetString("CurrentSettingsNotSet", resourceCulture)); 

				return (System.String)resourceCache["CurrentSettingsNotSet"].Target;
			}
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Parameter &apos;{0}&apos; does not have an associated condition since it corresponds to a variable.'
		/// </summary>
		public static System.String ParameterConditionNeedsAttribute
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("ParameterConditionNeedsAttribute", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["ParameterConditionNeedsAttribute"] = new WeakReference(ResourceManager.GetString("ParameterConditionNeedsAttribute", resourceCulture)); 

				return (System.String)resourceCache["ParameterConditionNeedsAttribute"].Target;
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parameter &apos;{0}&apos; does not have an associated condition since it corresponds to a variable.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatParameterConditionNeedsAttribute(object arg0)
		{
			return FormatParameterConditionNeedsAttribute(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Parameter &apos;{0}&apos; does not have an associated condition since it corresponds to a variable.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatParameterConditionNeedsAttribute(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, ParameterConditionNeedsAttribute, arg0);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Work With parent object must be a transaction.'
		/// </summary>
		public static System.String ParentMustBeTransaction
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("ParentMustBeTransaction", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["ParentMustBeTransaction"] = new WeakReference(ResourceManager.GetString("ParentMustBeTransaction", resourceCulture)); 

				return (System.String)resourceCache["ParentMustBeTransaction"].Target;
			}
		}

        public static System.String LicenseNotFound
        {
            get
            {
                WeakReference reference;
                resourceCache.TryGetValue("LicenseNotFound", out reference);
                if (reference == null || !reference.IsAlive)
                    resourceCache["LicenseNotFound"] = new WeakReference(ResourceManager.GetString("LicenseNotFound", resourceCulture));

                return (System.String)resourceCache["LicenseNotFound"].Target;
            }
        }

		/// <summary>
		/// Returns the System.String resource corresponding to 'Errors ocurred processing &apos;{0}&apos; template: {1}'
		/// </summary>
		public static System.String TemplateErrors
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("TemplateErrors", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["TemplateErrors"] = new WeakReference(ResourceManager.GetString("TemplateErrors", resourceCulture)); 

				return (System.String)resourceCache["TemplateErrors"].Target;
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Errors ocurred processing &apos;{0}&apos; template: {1}', fomatted using the specified arguments.
		/// </summary>
		public static string FormatTemplateErrors(object arg0, object arg1)
		{
			return FormatTemplateErrors(Culture, arg0, arg1);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Errors ocurred processing &apos;{0}&apos; template: {1}', fomatted using the specified arguments.
		/// </summary>
		public static string FormatTemplateErrors(IFormatProvider provider, object arg0, object arg1)
		{
			return String.Format(provider, TemplateErrors, arg0, arg1);
		}

		/// <summary>
		/// Returns the System.String resource corresponding to 'Unexpected IGridObject type: &apos;{0}&apos;.'
		/// </summary>
		public static System.String UnexpectedGridObjectType
		{
			get 
			{
				WeakReference reference;
				resourceCache.TryGetValue("UnexpectedGridObjectType", out reference);
				if (reference == null || !reference.IsAlive)
					resourceCache["UnexpectedGridObjectType"] = new WeakReference(ResourceManager.GetString("UnexpectedGridObjectType", resourceCulture)); 

				return (System.String)resourceCache["UnexpectedGridObjectType"].Target;
			}
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Unexpected IGridObject type: &apos;{0}&apos;.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatUnexpectedGridObjectType(object arg0)
		{
			return FormatUnexpectedGridObjectType(Culture, arg0);
		}

		/// <summary>
		/// Returns the string resource corresponding to 'Unexpected IGridObject type: &apos;{0}&apos;.', fomatted using the specified arguments.
		/// </summary>
		public static string FormatUnexpectedGridObjectType(IFormatProvider provider, object arg0)
		{
			return String.Format(provider, UnexpectedGridObjectType, arg0);
		}

        public static string VersionHPattern() {
            string v = String.Empty;
            try
            {
                v = HPattern.HPatternSettings.Get(Artech.Architecture.UI.Framework.Services.UIServices.KB.CurrentModel).Template.CompatibilidadeVersao;
            }
            catch (Exception e)
            {
            }
            return (String.IsNullOrEmpty(v) ? "" : String.Format("// WWHeurys Version [{0}]",v));
        }

        public static bool Debug()
        {
            return ResourceManager.GetString("Debug", resourceCulture) == "true" ? true : false;
        }

        public static bool TestTime()
        {
            return ResourceManager.GetString("TestTime", resourceCulture) == "true" ? true : false;
        }

        public static System.String UnknownCustomType
        {
            get
            {
                return (System.String)ResourceManager.GetString("UnknownCustomType", resourceCulture);
            }
        }

        public static string FormatUnknownCustomType(object arg0)
        {
            return FormatUnknownCustomType(Culture, arg0);
        }

        /// <summary>
        /// Returns the string resource corresponding to 'Unknown custom type: &apos;{0}&apos;.', fomatted using the specified arguments.
        /// </summary>
        public static string FormatUnknownCustomType(IFormatProvider provider, object arg0)
        {
            return String.Format(provider, UnknownCustomType, arg0);
        }

        public static System.String ValidationErrorActionCannotBeInGrid
        {
            get
            {
                return (System.String)ResourceManager.GetString("ValidationErrorActionCannotBeInGrid", resourceCulture);
            }
        }

        /// <summary>
        /// Returns the string resource corresponding to '{0} cannot be defined as &apos;In Grid&apos; since it is located in a tabular Tab.', fomatted using the specified arguments.
        /// </summary>
        public static string FormatValidationErrorActionCannotBeInGrid(object arg0)
        {
            return FormatValidationErrorActionCannotBeInGrid(Culture, arg0);
        }

        /// <summary>
        /// Returns the string resource corresponding to '{0} cannot be defined as &apos;In Grid&apos; since it is located in a tabular Tab.', fomatted using the specified arguments.
        /// </summary>
        public static string FormatValidationErrorActionCannotBeInGrid(IFormatProvider provider, object arg0)
        {
            return String.Format(provider, ValidationErrorActionCannotBeInGrid, arg0);
        }

        public static System.String CmdAddFilterVariable
        {
            get
            {
                return (System.String)ResourceManager.GetString("CmdAddFilterVariable", resourceCulture);
            }
        }

        public static System.String ConfirmAddFilterCondition
        {
            get
            {
                return (System.String)ResourceManager.GetString("ConfirmAddFilterCondition", resourceCulture);
            }
        }
        

	}
}