using System;
using System.Collections.Generic;
using System.Collections;
using System.IO;
using System.Text;
using System.Windows;

using Artech.Common.Collections;
using Artech.Common.Helpers.Strings;
using Artech.Common.Helpers.Templates;
using Artech.Architecture.Common.Objects;
using Artech.Genexus.Common;
using Artech.Genexus.Common.CustomTypes;
using Artech.Genexus.Common.Objects;
using Artech.Genexus.Common.Parts;
using Artech.Genexus.Common.Types;
using Artech.Packages.Patterns;
using Artech.Packages.Patterns.Objects;
using Heurys.Patterns.HPattern.Resources;
using Artech.Common.Properties;
using Artech.TemplateEngine;
using Heurys.Patterns.HPattern.Helpers;
using Artech.Genexus.Common.Wiki;

namespace Heurys.Patterns.HPattern
{
	internal static class HPatternTransactionUpdater
	{

        public const string k_GeneratedMarkerStart = "/* Generated by HPattern [Start] - Do not change */";
        public const string k_GeneratedMarkerEnd = "/* Generated by HPattern [End] - Do not change */";

		#region Apply Pattern

		public static void Apply(PatternInstance instance, Transaction transaction)
		{
			HPatternInstance wwInstance = HPatternInstance.Load(instance);
			HPatternSettings wwSettings = wwInstance.Settings;

			// Update rules and events.
            bool gera = wwInstance.Transaction.WebBC;
            /*
            bool gera = wwSettings.Template.DataEntryWebPanelBC;
            if (wwInstance.Transaction.DataEntryWebPanelBC.ToLower() == "true")
                gera = true;
            if (wwInstance.Transaction.DataEntryWebPanelBC.ToLower() == "false")
                gera = false;
            */

            bool overwrite = (wwInstance.Transaction.UpdateObject == TransactionElement.UpdateObjectValue.Overwrite);

            if (gera)
            {
                transaction.SetPropertyValue(Properties.TRN.BusinessComponent, true);
            }

            if (wwSettings.Template.TabFunction == SettingsTemplateElement.TabFunctionValue.TreeViewAnchor)
            {
                transaction.SetPropertyValue(Properties.TRN.Type, Properties.TRN.Type_Values.Component);
                transaction.SetPropertyValue(Properties.TRN.UrlAccess, Properties.TRN.UrlAccess_Values.Yes);
            }

            if (wwInstance.Transaction.UpdateObject != TransactionElement.UpdateObjectValue.DoNotUpdate)
            {

                UpdateProperties(wwInstance, wwSettings, transaction);
                UpdateVariables(wwInstance,wwSettings, transaction);
                ParserFactory.MergeRules(transaction.Rules, UpdateRules(wwInstance, wwSettings, transaction),overwrite);
                ParserFactory.MergeEvents(transaction.Events, UpdateEvents(wwInstance, wwSettings, transaction), overwrite);
                UpdateAttributes(wwInstance, wwSettings, transaction);


                if (wwInstance.Transaction.UpdateObject != TransactionElement.UpdateObjectValue.OnlyRulesEventsAndConditions)
                {
                    ParserFactory.MergeWebForm(transaction.WebForm, Heurys.Patterns.HPattern.Helpers.Template.TrnWebForm(transaction, wwSettings, wwInstance, false, "", false, wwInstance.Transaction));
                }

                if (wwInstance.DocumentationEnabled)
                {                    
                    TemplateInternal.DocumentationSave(transaction.Documentation, transaction, wwInstance, wwSettings);
                }
                
            }

        }

        #region Attribute

        private static void UpdateAttributes(HPatternInstance instance, HPatternSettings settings, Transaction transaction)
        {
            string picturedefault = settings.Template.PictureCharacterDefault;
            foreach (RowElement row in instance.Transaction.GetRows(""))
            {
                foreach (ColumnElement col in row.Columns)
                {
                    foreach (AttributeElement att in col.Attributes)
                    {
                        if (att.Attribute != null)
                        {
                            string picture = "";
                            if (att.Picture.ToLower() == "default")
                            {
                                picture = picturedefault;
                                if (picture != String.Empty && (att.Attribute.Type == eDBType.CHARACTER || att.Attribute.Type  == eDBType.VARCHAR))
                                {
                                    att.Attribute.SetPropertyValue(Properties.ATT.Picture, picture);
                                    att.Attribute.Save();                                    
                                }
                            }
                            else 
                            {
                                picture = att.Picture;
                                if (picture != String.Empty)
                                {
                                    att.Attribute.SetPropertyValue(Properties.ATT.Picture, picture);
                                    att.Attribute.Save();                                    
                                }
                            }
                        }
                    }
                }
            }
        }

        #endregion

        #region Properties

        private static void UpdateProperties(HPatternInstance instance, HPatternSettings settings, Transaction transaction)
		{

            WebPanel mTransaction = settings.MasterPages.Transaction;
            string AMP = SettingsThemeElement.SetObjectThemeValue.True;
            string ATema = settings.Theme.SetObjectTheme;
            Theme tTema = null;
            if (ATema != SettingsThemeElement.SetObjectThemeValue.False)
                tTema = settings.Theme.Theme;

            foreach (SettingsThemeMasterPageElement sis in settings.CustomThemeMasterPage)
            {
                if (transaction.Name.IndexOf(sis.Name, StringComparison.InvariantCultureIgnoreCase) >= 0)
                {
                    if (sis.SetMasterPage != SettingsThemeMasterPageElement.SetMasterPageValue.False)
                    {
                        mTransaction = sis.Transaction;
                        AMP = sis.SetMasterPage;
                    }
                    if (sis.SetTheme != SettingsThemeMasterPageElement.SetThemeValue.False)
                    {
                        tTema = sis.Theme;
                        ATema = sis.SetTheme;
                    }
                    break;
                }
            }

            if (transaction.IsPropertyDefault(Properties.TRN.MasterPage) || AMP == SettingsThemeElement.SetObjectThemeValue.Force)
            {
                if (mTransaction == null)
                {
                    transaction.SetPropertyValue(Properties.TRN.MasterPage, new WebPanelReference());
                }
                else
                {
                    transaction.SetPropertyValue(Properties.TRN.MasterPage, new WebPanelReference(mTransaction));
                }
            }

            if (tTema != null)
            {
                if (transaction.IsPropertyDefault(Properties.TRN.Theme) || ATema == SettingsThemeElement.SetObjectThemeValue.Force)
                {
                    transaction.SetPropertyValue(Properties.TRN.Theme, new KBObjectReference(tTema));
                }
            }

			if (instance.Levels.Count > 0 && instance.Levels[0].View != null)
			{
				if (instance.Levels[0].View.UseAsSearchViewer)
				{
                    try
                    {
                        
                        PropertyManager.PropertySpecDescriptor searchViewerProperty = transaction.GetPropertyDescriptor(Properties.TRN.SearchViewer);
                        if (searchViewerProperty.IsApplicable && searchViewerProperty.IsBrowsable && searchViewerProperty.IsDefaultValue)
                        {
                            WebPanel viewObject = WebPanel.Get(transaction.Model, instance.Levels[0].View.ObjectName);
                            if (viewObject != null)
                                transaction.SetPropertyValue(Properties.TRN.SearchViewer, new KBObjectReference(viewObject));
                        }
                        
                    }
                    catch (Exception e) {
                        LogLicense.LogEmpty(e.Message + e.StackTrace);                        
                    }
				}
			}
        }

        #endregion

        #region Variables

        private static void UpdateVariables(HPatternInstance instance, HPatternSettings settings, Transaction transaction)
		{

            foreach (RowElement row in instance.Transaction.GetRows(""))		
            {		
	            foreach (ColumnElement col in row.Columns) 
	            {		            
		            foreach (VariableElement vare in col.Variables)
		            {
			            if (vare.Domain != null) {
                            Variable var = AddVariable(transaction,vare.Name);
                            if (var != null)
                                var.DomainBasedOn = vare.Domain;

			            }
                        if (vare.Attribute != null)
                        {
                            Variable var = AddVariable(transaction, vare.Name);
                            if (var != null)
                                var.AttributeBasedOn = vare.Attribute;
                        }
		            }
	            }
            }

            Tab tabs = Tab.getTab(instance.Transaction.Form, transaction);

            tabs.VariablesTrn();

            /*
            Variable var2 = AddVariable(transaction, "MenuData");
            if (var2 != null)
                DataType.ParseInto(transaction.Model, "MenuData", var2);

            var2 = AddVariable(transaction, "MenuDataItem");
            if (var2 != null)
                DataType.ParseInto(transaction.Model, "MenuData.MenuDataItem", var2);
            */

            Variable var2 = AddVariable(transaction, "HTTPRequest");
            if (var2 != null)
                DataType.ParseInto(transaction.Model, "HttpRequest", var2);

            var2 = AddVariable(transaction, "n");
            if (var2 != null)
            {
                var2.Type = eDBType.NUMERIC;
                var2.Length = 1;
                var2.Decimals = 0;
                var2.Signed = false;
            }


			// Add variables for primary key.
			foreach (TransactionAttribute trnAtt in transaction.Structure.Root.PrimaryKey)
				AddBasedOnVariable(transaction, trnAtt.Name, trnAtt);

			// Add variables for Context.
			foreach (SettingsContextVariableElement contextVar in settings.Context)
			{
				Variable var = AddVariable(transaction, contextVar.Name);
				if (var != null)
					contextVar.SetType(var);
			}

			// Add variables for Security.
			//if (settings.Security.Enabled)
			//{
				var2 = AddVariable(transaction, "IsAuthorized");
				if (var2 != null)
					var2.Type = eDBType.Boolean;
			//}

            if (instance.Transaction.Parameters != null)
            {
                if (instance.Transaction.Parameters.Count > 0) {

                    foreach (ParameterElement pare in instance.Transaction.Parameters)
                    {
                        if (pare.IsAttribute)
                        {
                            TransactionAttribute ta = transaction.Structure.Root.GetAttribute(pare.Name);
                            if (ta != null)
                            {
                                AddBasedOnVariable(transaction, pare.Name, ta);
                            }
                        }
                        else
                        {
                            if (!String.IsNullOrEmpty(pare.DomainName))
                            {
                                Variable var = AddVariable(transaction, pare.Name.Replace("&",""));
                                if (var != null)
                                    var.DomainBasedOn = pare.Domain;
                            }
                        }
                    }
                }
            }

            /*
            if (instance.Transaction.Form.HasConditionalTabs())
            {
                Variable var = AddVariable(transaction, "conta");
                if (var != null)
                {
                    var.Type = eDBType.NUMERIC;
                    var.Length = 4;
                    var.Decimals = 0;
                    var.Signed = false;
                }
            }
            */

			if (settings.Template.UseTransactionContext)
			{
				Variable var = AddVariable(transaction, "TrnContext");
				if (var != null)
					DataType.ParseInto(transaction.Model, "TransactionContext", var);

				var = AddVariable(transaction, "WebSession");
				if (var != null)
					DataType.ParseInto(transaction.Model, "WebSession", var);

				if (HasContextAttributes(transaction))
				{
					// Add variables for Context Attributes (FKs excluding PKs atts)
					foreach (TransactionAttribute trnAtt in ContextAttributes(transaction))
						AddBasedOnVariable(transaction, "Insert_" + trnAtt.Name, trnAtt);

					var = AddVariable(transaction, "TrnContextAtt");
					if (var != null)
						DataType.ParseInto(transaction.Model, "TransactionContext.Attribute", var);
				}
			}
            addLinkCallBack(instance,transaction.Variables);

            MenuContext.get(instance.WebObject.Actions).Variables(transaction.Variables);

		}

        private static void addLinkCallBack(HPatternInstance instance,VariablesPart variables)
        {
            if (instance.Settings.Template.GenerateCallBackLink)
            {
                Variable var = AddVariable(variables,HPatternInstance.PARMCALLBACK);
                if (var != null)
                    var.DomainBasedOn = Domain.Get(instance.Model,HPatternInstance.PARMCALLBACK);
            }

        }

		private static void AddBasedOnVariable(Transaction transaction, string name, TransactionAttribute baseAttribute)
		{
			Variable var = AddVariable(transaction, name);
			if (var != null)
				var.AttributeBasedOn = baseAttribute;
		}
        
		private static Variable AddVariable(Transaction transaction, string name)
		{
			return AddVariable(transaction.Variables,name);
        }
		private static Variable AddVariable(VariablesPart variables, string name)
		{
			if (variables.GetVariable(name) == null)
			{
				Variable var = new Variable(variables);
				var.Name = name;
				variables.Variables.Add(var);
				return var;
			}

			return null;
        }

        #endregion

        #region Rules

        private static string UpdateRules(HPatternInstance instance, HPatternSettings settings, Transaction transaction)
        {
            StringBuilder rules = new StringBuilder();

            StringBuilder eventCodeAfterTrn = new StringBuilder();
            //if (transaction.IsBusinessComponent)
            //{
            rules.AppendLine("[web]");
            rules.AppendLine("{");
            //}

            // Add 'parm' rule
            rules.Append(instance.Transaction.GeraParm(false));

            // Add Prompts rule
            rules.Append(Helpers.Template.PromptRules(instance.Transaction.Form, settings));

            // Add 'primary key rules'
            foreach (TransactionAttribute trnAtt in transaction.Structure.Root.PrimaryKey)
            {
                rules.AppendFormat("\r\n{0} = &{0} if not &{0}.IsEmpty();", trnAtt.Name);

                bool edita = false;
                bool sai = false;

                foreach (RowElement row in Helpers.Template.GetRows(instance.Transaction, ""))
                {
                    foreach (ColumnElement col in row.Columns)
                    {
                        foreach (AttributeElement att in col.Attributes)
                        {
                            if (att.AttributeName == trnAtt.Name)
                            {
                                if (att.Readonly || att.Visible == false || row.Visible == false)
                                {
                                    edita = true;
                                                                      
                                }
                                sai = true;
                                break;  
                            }
                        }

                        if (sai)
                            break;

                    }

                    if (sai)
                        break;
                }

                if (edita || (transaction.Structure.Root.PrimaryKey.Count == 1 && trnAtt.Attribute.GetPropertyValue<bool>(Properties.ATT.Autonumber)))
                    rules.AppendFormat("\r\nnoaccept({0});", trnAtt.Name);
                else
                    rules.AppendFormat("\r\nnoaccept({0}) if not &{0}.IsEmpty();", trnAtt.Name);
            }

            // Add 'noprompt' rule.
            rules.AppendFormat("\r\nnoprompt({0});", GetList(transaction.Structure.Root.PrimaryKey));

            // Add context rules if applicable.
            if (settings.Template.UseTransactionContext)
            {
                rules.AppendLine();
                foreach (TransactionAttribute trnAtt in ContextAttributes(transaction))
                {
                    rules.AppendFormat("\r\n{0} = &Insert_{0} if &Mode = TrnMode.Insert and not &Insert_{0}.IsEmpty();", trnAtt.Name);
                    rules.AppendFormat("\r\nnoaccept({0}) if &Mode = TrnMode.Insert and not &Insert_{0}.IsEmpty();", trnAtt.Name);
                }
            }

            if (settings.Security.RuleCode != String.Empty) {
                rules.AppendLine(settings.Security.RuleCode);
            }

            rules.AppendLine();
            rules.Append(Helpers.Template.HMaskRuleSave(instance.Transaction, "", ""));
            rules.AppendLine();

            //if (transaction.IsBusinessComponent)
            //{
            rules.AppendLine("}");
            //}

            string ruledate = settings.Template.RuleDate;
            string valueruledate = settings.Template.ValueRuleDate;
            string ruledatetime = settings.Template.RuleDateTime;
            string valueruledatetime = settings.Template.ValueRuleDateTime;
            string defaultvalue = "";
            string defaultrule = "";

            


                IBaseCollection<RowElement> lista = new BaseCollection<RowElement>();
                lista = instance.Transaction.GetRows("",true,true);


                foreach (RowElement row in lista)
                {

                    foreach (ColumnElement col in row.Columns)
                    {
                        foreach (AttributeElement att in col.Attributes)
                        {
                            if (att.Attribute != null)
                            {

                                // Atributo Requerido

                                bool required = att.getRequired(transaction);

                                if (required)
                                {
                                    string message = settings.Template.RequiredNotNullMessage;
                                    if (att.RequiredMessage != String.Empty && att.RequiredMessage.ToLower() != "default")
                                    {
                                        message = att.RequiredMessage;
                                    }

                                    message = String.Format(message, (att.Description.Substring(0,1) == "=" ? att.Attribute.Description : att.Description ));

                                    if (att.RequiredAfterVal)
                                    {
                                        rules.AppendLine(String.Format("Error('{0}') if {1}.IsEmpty() on AfterValidate;", message, att.AttributeName));
                                    }
                                    else
                                    {
                                        rules.AppendLine(String.Format("Error('{0}') if {1}.IsEmpty();", message, att.AttributeName));
                                    }

                                }


                                // Regra para o atributo
                                defaultvalue = att.ValueRule;
                                if (defaultvalue == "<default>" || defaultvalue == String.Empty)
                                {
                                    defaultvalue = "";
                                    switch (att.Attribute.Type)
                                    {
                                        case eDBType.DATE:
                                            defaultvalue = valueruledate;
                                            break;

                                        case eDBType.DATETIME:
                                            defaultvalue = valueruledatetime;
                                            break;

                                    }
                                }

                                defaultrule = att.Rule;
                                if (defaultrule.ToLower() == "<default>")
                                {
                                    defaultrule = "";
                                    switch (att.Attribute.Type)
                                    {
                                        case eDBType.DATE:
                                            defaultrule = ruledate;
                                            break;

                                        case eDBType.DATETIME:
                                            defaultrule = ruledatetime;
                                            break;

                                    }
                                }

                                if (defaultvalue != String.Empty && defaultrule != String.Empty)
                                {

                                    switch (defaultrule)
                                    {
                                        case AttributeElement.RuleValue.DefaultRule: // "defaultrule":
                                            rules.AppendLine(String.Format("Default({0},{1});", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.AfterValidate: // "aftervalidate":
                                            rules.AppendLine(String.Format("{0} = {1} On AfterValidate;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.AfterInsert:
                                            rules.AppendLine(String.Format("{0} = {1} On AfterInsert;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.AfterUpdate:
                                            rules.AppendLine(String.Format("{0} = {1} On AfterUpdate;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.AfterDelete:
                                            rules.AppendLine(String.Format("{0} = {1} On AfterDelete;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.BeforeValidate:
                                            rules.AppendLine(String.Format("{0} = {1} On BeforeValidate;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.BeforeInsert:
                                            rules.AppendLine(String.Format("{0} = {1} On BeforeInsert;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.BeforeUpdate:
                                            rules.AppendLine(String.Format("{0} = {1} On BeforeUpdate;", att.AttributeName, defaultvalue));
                                            break;

                                        case AttributeElement.RuleValue.BeforeDelete:
                                            rules.AppendLine(String.Format("{0} = {1} On BeforeDelete;", att.AttributeName, defaultvalue));
                                            break;
                                    }
                                }


                            }
                        }
                    }
                }
            //}

            string codes = TemplateInternal.RuleCodes(TemplateInternal.CodeType.Transaction, settings);
            if (!String.IsNullOrEmpty(codes))
            {
                rules.Append(codes);
            }

            return AppendRules(transaction, rules.ToString());
        }

        private static string AppendRules(Transaction transaction, string rules)
        {
            return rules;
            /*
            string markedRules = k_GeneratedMarkerStart + Environment.NewLine + rules + Environment.NewLine + k_GeneratedMarkerEnd;

            // Check if generated block has changed.
            BasicParser parser = new BasicParser(transaction.Rules.Source);
            string oldMarkedRules = parser.GetBlock(new string[] { k_GeneratedMarkerStart }, new string[] { k_GeneratedMarkerEnd });
            if (oldMarkedRules == null || String.Compare(oldMarkedRules, markedRules, StringComparison.InvariantCultureIgnoreCase) != 0)
            {
                // Delete any previous generated block.
                DeleteGeneratedBlocks(parser);

                // Comment parm rule if it exists.
                parser.CommentBlock(new string[] { "parm", "(" }, new string[] { ";" });

                // Add new rules.
                transaction.Rules.Source = markedRules + Environment.NewLine + parser.Text;
            }
            */
        }
        

        #endregion

        #region Events

        private static string UpdateEvents(HPatternInstance instance, HPatternSettings settings, Transaction transaction)
		{
			BasicParser parser = new BasicParser("");

			DeleteGeneratedBlocks(parser);
            
            UpdateEventCodes(instance.Settings, parser);

            parser.InsertBefore(0, MenuContext.get(instance.WebObject.Actions).Events());

            // Se não vou gerar BC e tenho abas
            if (!instance.Transaction.WebBC && instance.Transaction.Form.Tabs.Count > 0)
            {
                Tab tabs = Tab.getTab(instance.Transaction.Form, transaction);
                parser.InsertBefore(0, tabs.Subs());
                //parser.InsertBefore(0, TemplateAbas.EventsExtra(instance.Transaction.Form));
            }
            UpdateEventActions(instance, settings, parser);
            UpdateEventPrompts(instance, settings,parser);
			UpdateEventAfterTrn(instance, transaction, parser);            
			UpdateEventStart(instance, settings, transaction, parser);
            
			return parser.Text;
		}

        private static void UpdateEventActions(HPatternInstance instance,HPatternSettings settings, BasicParser parser)
        {
            string tmp = Helpers.Template.TransactionActions(instance.Transaction);
            if (!String.IsNullOrEmpty(tmp))
            {
                StringBuilder eventCode = new StringBuilder();
                //eventCode.AppendLine(Indentation.Indent(k_GeneratedMarkerStart, 1));
                eventCode.Append(tmp);
                eventCode.Append(Environment.NewLine);
                //eventCode.AppendLine(Indentation.Indent(k_GeneratedMarkerEnd, 1));
                parser.InsertBefore(0, eventCode.ToString());
            }
        }

        private static void UpdateEventPrompts(HPatternInstance instance,HPatternSettings settings, BasicParser parser)
        {
            string tmp = Helpers.Template.PromptEvents(instance.Transaction.Form, settings);
            if (!String.IsNullOrEmpty(tmp))
            {
                StringBuilder eventCode = new StringBuilder();
                //eventCode.AppendLine(Indentation.Indent(k_GeneratedMarkerStart, 1));
                eventCode.Append(tmp);
                eventCode.Append(Environment.NewLine);
                //eventCode.AppendLine(Indentation.Indent(k_GeneratedMarkerEnd, 1));
                parser.InsertBefore(0, eventCode.ToString());
            }

        }

		private static void UpdateEventAfterTrn(HPatternInstance instance, Transaction transaction, BasicParser parser)
		{
			StringBuilder eventCodeAfterTrn = new StringBuilder();
			//if (transaction.IsBusinessComponent)
			//{
				eventCodeAfterTrn.AppendLine("[web]");
				eventCodeAfterTrn.AppendLine("{");
			//}

                if (instance.Settings.Template.GenerateCallBackLink)
                {
                    eventCodeAfterTrn.AppendLine(Indentation.Indent(String.Format("If &{0}.IsEmpty()", HPatternInstance.PARMCALLBACK), 1));
                    eventCodeAfterTrn.AppendLine(Indentation.Indent("Return", 2));
                    eventCodeAfterTrn.AppendLine(Indentation.Indent("Else", 1));
                    eventCodeAfterTrn.AppendLine(Indentation.Indent(String.Format("PrLinkCallBack(&{0})", HPatternInstance.PARMCALLBACK), 2));
                    eventCodeAfterTrn.AppendLine(Indentation.Indent("EndIf", 1));
                    eventCodeAfterTrn.AppendLine("");
                }
                else
                {

                    bool appendBlankLine = false;
                    AppendRedirection(instance, eventCodeAfterTrn, "Insert", instance.AfterInsert, ref appendBlankLine);
                    AppendRedirection(instance, eventCodeAfterTrn, "Update", instance.AfterUpdate, ref appendBlankLine);

                    // Delete is special because we cannot return to caller when deleting from a view.
                    if (!AppendRedirection(instance, eventCodeAfterTrn, "Delete", instance.AfterDelete, ref appendBlankLine))
                    {
                        SelectionElement emergencyRedirection;
                        if (instance.Settings.Template.UseTransactionContext && CanRedirectToSelection(instance, out emergencyRedirection))
                        {
                            if (appendBlankLine)
                                eventCodeAfterTrn.AppendLine(String.Empty);

                            eventCodeAfterTrn.AppendLine("If (&Mode = TrnMode.Delete and not &TrnContext.CallerOnDelete)");
                            eventCodeAfterTrn.AppendLine(String.Format("\t{0}.Call({1})", emergencyRedirection.ObjectName, emergencyRedirection.Parameters.List()));
                            eventCodeAfterTrn.Append("Endif");
                        }
                    }

                }

                //if (transaction.IsBusinessComponent)
                //{
                eventCodeAfterTrn.AppendLine("");
                eventCodeAfterTrn.Append("}");
                //}
                
			// Add the event (or modify the existing one).
			UpdateEventCode(parser, new string[] { "After", "Trn" }, eventCodeAfterTrn.ToString());
		}

        private static void UpdateEventCodes( HPatternSettings settings, BasicParser parser)
        {
            string codes = TemplateInternal.EventCodes(TemplateInternal.CodeType.Transaction, settings);
            if (!String.IsNullOrEmpty(codes))
            {

                StringBuilder eventBuilder = new StringBuilder();
                //eventBuilder.AppendLine(k_GeneratedMarkerStart);
                eventBuilder.AppendLine(codes);
                //eventBuilder.AppendLine(k_GeneratedMarkerEnd);
                eventBuilder.Append(Environment.NewLine);
                parser.InsertBefore(0, eventBuilder.ToString());

            }           
        }

		private static void UpdateEventStart(HPatternInstance instance, HPatternSettings settings, Transaction transaction, BasicParser parser)
		{
			StringBuilder eventCodeStart = new StringBuilder(100);

            eventCodeStart.AppendLine(Messages.VersionHPattern());

			Generator.GeneratorParameters parameters = new Generator.GeneratorParameters();
			DefaultProvider.PrepareTemplateParameters(parameters);
			parameters.Properties["Settings"] = settings;
            parameters.Properties["tipo"] = 0;

			AppendTemplateOutput(eventCodeStart, "SubLoadContext", parameters);            

            //if (settings.Security.Enabled)
            //{

            eventCodeStart.AppendLine("[web]");
            eventCodeStart.AppendLine("{");

            parameters.Properties["Instance"] = instance;
            parameters.Properties["IsTransaction"] = true;

            AppendTemplateOutput(eventCodeStart, "SubCheckSecurity", parameters);


            //}

            if (settings.Security.EventStart != String.Empty)
            {
                eventCodeStart.AppendLine("");
                eventCodeStart.AppendLine(settings.Security.EventStart);
            }

            eventCodeStart.AppendLine();
            eventCodeStart.Append("}");

			if (settings.Template.UseTransactionContext)
			{
				if (eventCodeStart.Length > 0)
					eventCodeStart.AppendLine();

				eventCodeStart.AppendLine("&TrnContext.FromXml(&WebSession.Get(!\"TrnContext\"))");

				if (HasContextAttributes(transaction))
				{
					eventCodeStart.AppendLine("If (&TrnContext.TransactionName = &Pgmname and &Mode = TrnMode.Insert)");
					eventCodeStart.AppendLine("\tFor &TrnContextAtt in &TrnContext.Attributes");

					bool first = true;
					foreach (TransactionAttribute icAtt in ContextAttributes(transaction))
					{
						if (first)
						{
							eventCodeStart.AppendLine("\t\tDo Case");
							first = false;
						}
						eventCodeStart.AppendFormat("\t\t\t// When inserting with instantiated {0}\r\n", icAtt.Name);
						eventCodeStart.AppendFormat("\t\t\tCase &TrnContextAtt.AttributeName = !\"{0}\"\r\n", icAtt.Name);
						eventCodeStart.AppendFormat("\t\t\t\t&Insert_{0}.FromString(&TrnContextAtt.AttributeValue)\r\n", icAtt.Name);
					}
					if (!first)
						eventCodeStart.AppendLine("\t\tEndcase");

					eventCodeStart.AppendLine("\tEndfor");
					eventCodeStart.Append("Endif");
				}
			}

            if (settings.Template.EventStart != String.Empty) {
                eventCodeStart.AppendLine("");
                eventCodeStart.AppendLine(settings.Template.EventStart);
            }

            eventCodeStart.AppendLine("");
            eventCodeStart.AppendLine("[web]");
            eventCodeStart.AppendLine("{");


                IBaseCollection<RowElement> lista = instance.Transaction.GetRows("",true,true);


                foreach (RowElement row in lista)
                {

                    foreach (ColumnElement col in row.Columns)
                    {
                        foreach (VariableElement var in col.Variables)
                        {
                            if (var.Domain != null || var.Attribute != null)
                            {
                                if (!var.Visible || !row.Visible)
                                {
                                    eventCodeStart.AppendLine("");
                                    eventCodeStart.AppendFormat("&{0}.Visible = false", var.Name);
                                }
                                if (!String.IsNullOrEmpty(var.LoadCode))
                                {
                                    eventCodeStart.AppendLine("");
                                    eventCodeStart.AppendLine(var.LoadCode);
                                }
                                if (!String.IsNullOrEmpty(var.LinksEventStart))
                                {
                                    eventCodeStart.AppendLine("");
                                    eventCodeStart.AppendLine(var.LinksEventStart);
                                }

                            }
                        }

                        foreach (AttributeElement att in col.Attributes)
                        {
                            if (att.Attribute != null)
                            {
                                if (!att.Visible || !row.Visible)
                                {
                                    eventCodeStart.AppendLine("");
                                    eventCodeStart.AppendFormat("{0}.Visible = false", att.AttributeName);

                                }
                                if (!String.IsNullOrEmpty(att.LinksEventStart))
                                {
                                    eventCodeStart.AppendLine("");
                                    eventCodeStart.AppendLine(att.LinksEventStart);
                                }
					            if (!String.IsNullOrEmpty(att.EventStart))
					            {
                                    eventCodeStart.AppendLine("");
                                    eventCodeStart.AppendLine(String.Format(att.EventStart, att.AttributeName, att.AttributeName));
					            }
                            }
                        }

                        foreach (TextElement text in col.Texts)
                        {

                            if (!text.Visible || !row.Visible)
                            {
                                eventCodeStart.AppendLine("");
                                eventCodeStart.AppendFormat("{0}.Visible = false", text.Name);
                            }
                        }
                    }
                }
	        //}

            bool setFocus = instance.Transaction.GetSetFocus;
            /*
                settings.Template.TransactionSetFocus;
            if (instance.Transaction.SetFocus.ToLower() == "true")
                setFocus = true;
            if (instance.Transaction.SetFocus.ToLower() == "true")
                setFocus = false;
            */

            Artech.Genexus.Common.Objects.Attribute setFocusAtt = instance.Transaction.SetFocusAttribute;
            if (setFocusAtt == null && transaction.Structure.Root.DescriptionAttribute != null)
            {
                setFocusAtt = transaction.Structure.Root.DescriptionAttribute.Attribute;
            }

            if (setFocus && setFocusAtt != null) 
            {
                eventCodeStart.AppendLine();
                eventCodeStart.AppendLine(setFocusAtt.Name + ".SetFocus()");
            }

            eventCodeStart.AppendLine("");

            // Se não vou gerar BC e tenho abas
            if (!instance.Transaction.WebBC && instance.Transaction.Form.Tabs.Count > 0)
            {
                Tab tabs = Tab.getTab(instance.Transaction.Form, transaction);
                eventCodeStart.Append(tabs.Events());            
                //eventCodeStart.Append( TemplateAbas.Start(instance.Transaction.Form));            
            }

            eventCodeStart.AppendLine(Helpers.Template.HMaskEventStart(instance.Transaction, "", false));

            eventCodeStart.AppendLine("}");

            if (!String.IsNullOrEmpty(instance.Transaction.EventStart))
            {
                eventCodeStart.AppendLine(Indentation.Indent(instance.Transaction.EventStart, 1));
            }

			if (eventCodeStart.Length > 0)
				UpdateEventCode(parser, new string[] { "Start" }, eventCodeStart.ToString());
		}
        
		private static void UpdateEventCode(BasicParser parser, string[] eventName, string eventCode)
		{
			StringBuilder eventBuilder = new StringBuilder();
			eventBuilder.AppendLine("Event " + String.Join(" ", eventName));
			bool isNewEvent = true;

			// Keep the current event code, if any.
			List<string> beginEvent = new List<string>();

			beginEvent.Add("Event");
			beginEvent.AddRange(eventName);
			string currentEvent = parser.GetBlock(beginEvent.ToArray(), new string[] { "EndEvent" }, 0, true);
			if (currentEvent != null)
			{
				isNewEvent = false;
				string eventNameLastToken = eventName[eventName.Length - 1];
				int eventBodyStart = currentEvent.ToLower().IndexOf(eventNameLastToken.ToLower()) + eventNameLastToken.Length;
				int eventBodyEnd = currentEvent.ToLower().IndexOf("endevent");

				if (eventBodyStart != -1 && eventBodyEnd != -1)
				{
					string currentEventCode = currentEvent.Substring(eventBodyStart, eventBodyEnd - eventBodyStart);
					if (currentEventCode.Trim() != String.Empty)
					{
						currentEventCode = currentEventCode.TrimStart(Environment.NewLine.ToCharArray());
						currentEventCode = currentEventCode.TrimEnd(Environment.NewLine.ToCharArray());
						eventBuilder.AppendLine(currentEventCode);
					}
				}
			}

			// Add the desired code.
			//eventBuilder.AppendLine(Indentation.Indent(k_GeneratedMarkerStart, 1));
			eventBuilder.AppendLine(Indentation.Indent(eventCode, 1));
			//eventBuilder.AppendLine(Indentation.Indent(k_GeneratedMarkerEnd, 1));
			eventBuilder.Append("EndEvent");

			if (isNewEvent)
			{
				eventBuilder.Append(Environment.NewLine);
				parser.InsertBefore(0, eventBuilder.ToString());
			}
			else
			{
				parser.ReplaceBlock(beginEvent.ToArray(), new string[] { "EndEvent" }, eventBuilder.ToString());
			}
        }

        #endregion

        #region Misc

        private static IEnumerable<TransactionAttribute> ContextAttributes(Transaction trn)
        {
            foreach (TransactionAttribute trnAtt in trn.Structure.Root.ForeignKeyAttributes)
                if (!trn.Structure.Root.PrimaryKey.Contains(trnAtt))
                    yield return trnAtt;
        }

        private static bool HasContextAttributes(Transaction trn)
        {
            return !Enumerable.IsEmpty(ContextAttributes(trn));
        }

        private static string GetList(IList<TransactionAttribute> attributes)
        {
            List<string> names = new List<string>();
            foreach (TransactionAttribute att in attributes)
                names.Add(att.Name);
            return String.Join(",", names.ToArray());
        }

        private static bool AppendRedirection(HPatternInstance instance, StringBuilder sb, string mode, string option, ref bool appendBlankLine)
        {
            string redirectionLine = null;

            SelectionElement selection;
            if (option == HPatternInstance.AfterInsertValue.GoToSelection && CanRedirectToSelection(instance, out selection))
                redirectionLine = String.Format("\t{0}.Call({1})", selection.ObjectName, selection.Parameters.List());

            ViewElement view;
            if (option == HPatternInstance.AfterInsertValue.GoToView && CanRedirectToView(instance, out view))
            {
                redirectionLine = String.Format("\t{0}.Call({1})", view.ObjectName, view.Parameters.ListView());
            }

            if (redirectionLine != null)
            {
                if (appendBlankLine)
                    sb.AppendLine(String.Empty);

                sb.AppendLine(String.Format("If (&Mode = TrnMode.{0})", mode));
                sb.AppendLine(redirectionLine);
                sb.Append("Endif");

                appendBlankLine = true;
                return true;
            }

            return false;
        }

        internal static string GetObjectName(Generator.GeneratorParameters parameters)
        {
            string nome = String.Empty;
            foreach (KeyValuePair<string, object> item in parameters.Properties)
            {
                if (item.Value is KBObject)
                {
                    nome = ((KBObject)item.Value).Name;
                    break;
                }
            }
            return nome;
        }

        public static void AppendTemplateOutput(StringBuilder stringBuilder, string templateName, Generator.GeneratorParameters parameters)
        {
            if (!templateName.ToLower().EndsWith(".dll"))
                templateName += ".dll";
            
            string templatesBasePath = Path.Combine(HPatternPattern.Definition.DefinitionBasePath, "Templates");
            string templatePath = Path.Combine(templatesBasePath, templateName);
            string mObjectName = GetObjectName(parameters);
            List<string> templateErrors = new List<string>();
            string output = "";
            try
            {
                output = Generator.GenerateToString(templatePath, parameters, out templateErrors);
                if (templateErrors.Count > 0)
                    throw new TemplateException(mObjectName+": "+Messages.FormatTemplateErrors(templateName, String.Join(String.Empty, templateErrors.ToArray())));

            }
            catch (Exception ex)
            {
                throw new TemplateException(Messages.FormatTemplateErrors(templateName, String.Join(String.Empty, templateErrors.ToArray())), (ex.InnerException != null ? ex.InnerException : ex), mObjectName);
            }

            stringBuilder.Append(output);
        }

        private static bool CanRedirectToSelection(HPatternInstance instance, out SelectionElement selection)
        {
            // Do we have an appropriate selection element?
            if (instance.Levels.Count > 0 &&
                instance.Levels[0].Selection != null &&
                CanRedirectTo(instance.Levels[0].Selection))
            {
                selection = instance.Levels[0].Selection;
                return true;
            }

            selection = null;
            return false;
        }

        private static bool CanRedirectToView(HPatternInstance instance, out ViewElement view)
        {
            // Do we have an appropriate view element?
            if (instance.Levels.Count > 0 &&
                instance.Levels[0].View != null &&
                CanRedirectTo(instance.Levels[0].View))
            {
                view = instance.Levels[0].View;
                return true;
            }

            view = null;
            return false;
        }

        private static bool CanRedirectTo(IHPatternComponent component)
        {
            // Does it have acceptable (or no) parameters?
            bool temParm = false; // Verifica se os parametros da selection existem na transação, se existir, permite redirectionar,
            if (component is SelectionElement)
            {
                foreach (ParameterElement pare in component.Parameters)
                {
                    ParameterElement pare2 = component.TrnElement.Parameters.FindParameter(pare.Name);
                    if (pare2 == null)
                    {
                        temParm = false;
                        break;
                    }
                    else
                    {
                        temParm = true;
                    }

                }
            }
            
            if (component.Parameters.IsOnlyAttributes || temParm)
            {
                // Is it an existing webpanel?
                WebPanel currentObject = WebPanel.Get(component.Instance.Model, component.ObjectName);
                if (currentObject != null)
                {
                    // Can it be called?
                    string objectType = currentObject.GetPropertyValue<string>(Properties.WBP.Type);
                    string urlAccess = currentObject.GetPropertyValue<string>(Properties.WBP.UrlAccess);

                    if (objectType == Properties.WBP.Type_Values.WebPage ||
                        objectType == Properties.WBP.Type_Values.Component && urlAccess == Properties.WBP.UrlAccess_Values.Yes)
                    {
                        return true;
                    }
                }
            }

            return false;
        }

        #endregion

        #endregion

        #region Remove Pattern

        public static void Clear(PatternInstance instance, Transaction transaction)
		{
			// HPatternInstance wwInstance = HPatternInstance.Load(instance);
			ClearProperties(transaction);
			ClearRules(transaction);
			ClearEvents(transaction);
			ClearVariables(transaction);
		}

		private static void ClearProperties(Transaction transaction)
		{
			transaction.ResetProperty(Properties.TRN.MasterPage);
			transaction.ResetProperty(Properties.TRN.SearchViewer);
		}

		private static void ClearVariables(Transaction transaction)
		{
			foreach (TransactionAttribute trnAtt in transaction.Structure.Root.PrimaryKey)
			{
				Variable var = transaction.Variables.GetVariable(trnAtt.Name);
				if (var != null)
				{
					// Remove it (unless it's used in the web form or in other parts of the code).


                    if (!transaction.WebForm.Variables.TrueForAll<Variable>(delegate(Variable v) { return v.Name == var.Name; }) &&
						!transaction.Events.Source.Contains("&" + var.Name) &&
						!transaction.Rules.Source.Contains("&" + var.Name))
	    			{
    					transaction.Variables.Remove(var);
					}
				}
			}
		}

		private static void ClearRules(Transaction transaction)
		{
			BasicParser parser = new BasicParser(transaction.Rules.Source);
			DeleteGeneratedBlocks(parser);
			transaction.Rules.Source = parser.Text;
		}

		private static void ClearEvents(Transaction transaction)
		{
			BasicParser parser = new BasicParser(transaction.Events.Source);
			DeleteGeneratedBlocks(parser);
			transaction.Events.Source = parser.Text;
		}

		private static void DeleteGeneratedBlocks(BasicParser parser)
		{
			bool keepDeleting = true;
			while (keepDeleting)
				keepDeleting = parser.DeleteBlock(new string[] { k_GeneratedMarkerStart }, new string[] { k_GeneratedMarkerEnd });
		}

		#endregion
	}
}
